# <span style="font-family:Papyrus; font-size:4em; color:Green;">Herensuge</span>

## **Things to Remember:**

1) Read the getting started before reading this write-up.

2) All file paths shown are based on the computer used in this write-up.

3) Use the Resource page/pdf to see a list all websites and programs used in this write-up.

## <font color=green>Herensuge 1</font>

Ella's PC has been infected with ransomware. We think it happened after an email was sent to Amaya and then forwarded to Ella on August 23, 2018. Find the artifacts in the available smtp sessions. What is the email address of the sender?

### Solution

The question gives two critical pieces of information. First, the date of August 23, 2018. Second, that Amaya forwarded the malicious email to Ella. With that information, navigate to the SMTP files for Ella. All the smtp files are in Epoch time and will have to be converted.

Let's convert the file times and display only files for August 23:

In [12]:
[string[]]$array = Get-ChildItem "C:\Users\Administrator\Artifacts\smtp\ebeltze" -Name

for($i=0; $i -le $array.GetUpperBound(0); $i++)
{
    $date = (Get-Date 01.01.1970)+([System.TimeSpan]::fromseconds($array[$i]))
    #$date
    if($date -like "*08/23/2018*")
    {
        write-host $array[$i] "-->" $date
    }
}

1535048736 --> 8/23/2018 6:25:36 PM
1535049125 --> 8/23/2018 6:32:05 PM
1535049575 --> 8/23/2018 6:39:35 PM
1535052757 --> 8/23/2018 7:32:37 PM
1535064592 --> 8/23/2018 10:49:52 PM


Since this email was forwarded to Ella from Amaya, let's look for files that only include "Fwd:": 

In [13]:
Select-String -Path "..\smtp\ebeltze\15350*" -Pattern 'Fwd:'


C:\Users\Administrator\Artifacts\smtp\ebeltze\1535052757:12:Subject: Fwd: Import Updates for your Hazia Equipment
C:\Users\Administrator\Artifacts\smtp\ebeltze\1535064592:12:Subject: Fwd: UPDATED: Import Updates for your Hazia 
Equipment




Two files include the "Fwd:" text, let's analyze these smtp files separately:

In [5]:
Get-Content "..\smtp\ebeltze\1535052757" -First 60

Return-Path: <alabank@orko.net>
Delivered-To: ebeltze@orko.net
Received: from _ (localhost [127.0.0.1])
	by mail.orko.net (Postfix) with ESMTPSA id D6250182093
	for <ebeltze@orko.net>; Thu, 23 Aug 2018 12:32:36 -0700 (PDT)
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="=_a729b4cf3ca8fd9845339fcfa53284fa"
Date: Thu, 23 Aug 2018 12:32:36 -0700
From: alabank@orko.net
To: Ella Beltzetan <ebeltze@orko.net>
Subject: Fwd: Import Updates for your Hazia Equipment
Organization: Orko Electric
In-Reply-To: <333be276c38f178aa7406ebe9f1cb801@hazia.com>
References: <333be276c38f178aa7406ebe9f1cb801@hazia.com>
Message-ID: <b8b70f6c12894433a81ea4c9ee78e886@orko.net>
X-Sender: alabank@orko.net
User-Agent: Roundcube Webmail

--=_a729b4cf3ca8fd9845339fcfa53284fa
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
 format=flowed

Ella,

I think I have wrapped things up.

I let Atton know he's in charge while I'm out.

In the mean I need you to run these updates for the 

In [6]:
Get-Content "..\smtp\ebeltze\1535064592" -First 60

Return-Path: <alabank@orko.net>
Delivered-To: ebeltze@orko.net
Received: from _ (localhost [127.0.0.1])
	by mail.orko.net (Postfix) with ESMTPSA id 39AD7182068
	for <ebeltze@orko.net>; Thu, 23 Aug 2018 15:49:48 -0700 (PDT)
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="=_a53a75e3bb55af5a50dea77d87e2bef9"
Date: Thu, 23 Aug 2018 15:49:48 -0700
From: alabank@orko.net
To: Ella Beltzetan <ebeltze@orko.net>
Subject: Fwd: UPDATED: Import Updates for your Hazia Equipment
Organization: Orko Electric
In-Reply-To: <f8f30025a11a8c40786d138dce011c7b@hazia.com>
References: <f8f30025a11a8c40786d138dce011c7b@hazia.com>
Message-ID: <a0c1b7bd7af4eb0899acca52fbe01231@orko.net>
X-Sender: alabank@orko.net
User-Agent: Roundcube Webmail

--=_a53a75e3bb55af5a50dea77d87e2bef9
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
 format=flowed

Ugh...apparently Hektor sent a broken update. Here's the new one for our 
Hazia equipment.

So much for taking a moment for myself.



Both emails are from the same sender (helizondo@hazia.com) stating that a software update needs to be installed.

#### Answer: helizondo@hazia.com

## <font color=green>Herensuge 2</font>

What is the name of the script that infected Ella's PC with ransomware (include the extension in the script name)?

### Solution

Start from the two smtp files from Herensuge 1:

In [9]:
Get-Content "..\smtp\ebeltze\1535052757" -First 70

Return-Path: <alabank@orko.net>
Delivered-To: ebeltze@orko.net
Received: from _ (localhost [127.0.0.1])
	by mail.orko.net (Postfix) with ESMTPSA id D6250182093
	for <ebeltze@orko.net>; Thu, 23 Aug 2018 12:32:36 -0700 (PDT)
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="=_a729b4cf3ca8fd9845339fcfa53284fa"
Date: Thu, 23 Aug 2018 12:32:36 -0700
From: alabank@orko.net
To: Ella Beltzetan <ebeltze@orko.net>
Subject: Fwd: Import Updates for your Hazia Equipment
Organization: Orko Electric
In-Reply-To: <333be276c38f178aa7406ebe9f1cb801@hazia.com>
References: <333be276c38f178aa7406ebe9f1cb801@hazia.com>
Message-ID: <b8b70f6c12894433a81ea4c9ee78e886@orko.net>
X-Sender: alabank@orko.net
User-Agent: Roundcube Webmail

--=_a729b4cf3ca8fd9845339fcfa53284fa
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
 format=flowed

Ella,

I think I have wrapped things up.

I let Atton know he's in charge while I'm out.

In the mean I need you to run these updates for the 

In [10]:
Get-Content "..\smtp\ebeltze\1535064592" -First 60

Return-Path: <alabank@orko.net>
Delivered-To: ebeltze@orko.net
Received: from _ (localhost [127.0.0.1])
	by mail.orko.net (Postfix) with ESMTPSA id 39AD7182068
	for <ebeltze@orko.net>; Thu, 23 Aug 2018 15:49:48 -0700 (PDT)
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="=_a53a75e3bb55af5a50dea77d87e2bef9"
Date: Thu, 23 Aug 2018 15:49:48 -0700
From: alabank@orko.net
To: Ella Beltzetan <ebeltze@orko.net>
Subject: Fwd: UPDATED: Import Updates for your Hazia Equipment
Organization: Orko Electric
In-Reply-To: <f8f30025a11a8c40786d138dce011c7b@hazia.com>
References: <f8f30025a11a8c40786d138dce011c7b@hazia.com>
Message-ID: <a0c1b7bd7af4eb0899acca52fbe01231@orko.net>
X-Sender: alabank@orko.net
User-Agent: Roundcube Webmail

--=_a53a75e3bb55af5a50dea77d87e2bef9
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
 format=flowed

Ugh...apparently Hektor sent a broken update. Here's the new one for our 
Hazia equipment.

So much for taking a moment for myself.



Both files include an attachment named `called.vbs`. 

#### Answer:  caller.vbs

## <font color=green>Herensuge 3</font>

Extract out the VBScript from the email SMTP session. What file did the VBScript create and execute?

### Solution

Looking back at the two smtp files from Herensuge 2, the second email "1535064592" with the corrected update script seems off. The email has no greeting, broken grammar, and no formal ending. When compared to the first email "1535052757" it seems almost like a different person. Knowing that Ella probably installed the VBScript from the second email, that's the first place to start.

Extract the "caller.vbs" file from Ella's "1535064592" smtp file. This can be down by base64 decoding the attachment manually from the email or with the following `carve.py` python script which with the following commands below:

In [2]:
python ../carve.py "..\smtp\ebeltze\1535064592"

[+] Email part ID 0: None
==> Content Type: multipart/mixed

[+] Email part ID 1: None
==> Content Length in bytes: 535
==> Content Type: text/plain

[+] Email part ID 2: caller.vbs
==> Content Length in bytes: 6553346
==> Content Type: text/plain



The VBScript file in question has the ID 2 which was passed in the command below to extract it:

In [1]:
python ../carve.py "..\smtp\ebeltze\1535064592" 2

[+] Email part ID 0: None
==> Content Type: multipart/mixed

[+] Email part ID 1: None
==> Content Length in bytes: 535
==> Content Type: text/plain

[+] Email part ID 2: caller.vbs
==> Content Length in bytes: 6553346
==> Content Type: text/plain

Dumping email part ID 2 with filename caller.vbs...
Successfully dumped file caller.vbs


Since the file is larger, open it in sublime and scroll to the bottom. We can look at the bottom of the code with the following command:

In [ ]:
Get-Content "C:\Users\Administrator\Artifacts\caller.vbs" -Last 9

![Heren](pics/Heren7.png)

The VBScript creates a file called `aisoudfwemidf.ps1` and executes it.

#### Answer: aisoudfwemidf.ps1

## <font color=green>Herensuge 4</font>

What file did the Powershell script create and execute?

### Solution

We need to delete the code in the `caller.vbs` script that executes and deletes the Powershell program:

![Heren](pics/Heren4-1.png)

In [13]:
$original_file = '..\caller.vbs'
$destination_file = "..\caller_clean.vbs"
(Get-Content $original_file) | Foreach-Object {
    $_.replace('SET oShell = WScript.CreateObject("Wscript.Shell")', '').replace('currentCommand = "powershell.exe -WindowStyle Hidden .\aisoudfwemidf.ps1"', '').replace('oShell.run currentCommand,1,True', '').replace('objFSO.DeleteFile "aisoudfwemidf.ps1"', '')
    } | Set-Content $destination_file 

Now execute the `caller_clean.vbs` script and a Powershell file will be created.

Since the file is larger, open `aisoudfwemidf.ps1` in sublime and scroll to the bottom. We can look at the bottom of the code with the following command:

In [19]:
Get-Content "..\aisoudfwemidf.ps1" -Last 7

# end executable
$filename = 'aisoudfwemidf.exe'

$bytes = [Convert]::FromBase64String($b64)
[IO.File]::WriteAllBytes($filename, $bytes)
Start-Process -FilePath $filename -Wait
Remove-Item $filename


![Heren](pics/Heren4-2.png)

The Powershell script creates and executes a file called `aisoudfwemidf.exe`.

#### Answer:  aisoudfwemidf.exe

## <font color=green>Herensuge 5</font>

Time to do some reverse engineering! At first glance, the final executable is packed. (https://en.wikipedia.org/wiki/Executable_compression). What popular packer does this executable use?

### Solution

We need to delete the code in the `aisoudfwemidf.ps1` script that executes and deletes the `aisoudfwemidf.exe`file: 

In [2]:
Get-Content "..\aisoudfwemidf.ps1" -Last 6

$filename = 'aisoudfwemidf.exe'

$bytes = [Convert]::FromBase64String($b64)
[IO.File]::WriteAllBytes($filename, $bytes)
Start-Process -FilePath $filename -Wait
Remove-Item $filename


![Heren](pics/Heren5-1.png)

Now execute the `aisoudfwemidf.exe` script and an EXE file will be created. This can be done with the following command:

In [ ]:
Invoke-Item "..\aisoudfwemidf.ps1"

Open the application **PEiD** and open the **aisoudfwemidf.exe** file in it. You'll notice that the EP Section listes UPX. UPX is a popular packer.

![Heren](pics/Heren5-2.png)

#### Answer: UPX

## <font color=green>Herensuge 6</font>

Unpack the executable. What programming language was the original executable written in?

### Solution

Knowing that the executable was packed with UPX, we can use UPX to decompress the executable with this command: 

In [1]:
C:\Tools\upx-3.95-win64\upx.exe -d "..\aisoudfwemidf.exe"

                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   3716929 <-   3685185   99.15%    win32/pe     aisoudfwemidf.exe

Unpacked 1 file.


Open the decompressed file in IDA.

Locate the strings panel. While scrolling through his panel, you'll notice that python is called on many times. Specifically a python dll. 

![Heren](pics/Heren6-1.png)

#### Answer: Python

## <font color=green>Herensuge 7</font>

What is the prefix preceding the random number in the name of the temporary directory created by the ransomware?

### Solution

Continue examining the decompressed `aisoudfwemidf.exe` file in IDA. 

The question states that a temporary directory was created by the ransomware. In the function windows, you'll want to look for a new directory being created or mkdir:

![Heren](pics/Heren7-1.png)

Double clicking the function will take you to the IDA View-A where you can select "\_mkdir" and press x to list the cross references (where that function was called from). 

![Heren](pics/Heren7-2.png)

From there you'll notice that the "\_mkdir" is using a "\_MEI%d" to pre-pend the file path.

![Heren](pics/Heren7-3.png)

#### Answer: _MEI

## <font color=green>Herensuge 8</font>

Your answers to the last two question should give you more hints as to how the ransomware was packed. What tool/library was used in packing the ransomware?

### Solution

Look up the last two answers **_ MEI and Python (nospace between the underscore and MEI)** and the results give the tool/library.

![Heren](pics/Heren27.png)


#### Answer: PyInstaller

## <font color=green>Herensuge 9</font>

Extract the original Python script(s). How is the wallpaper image encoded?

### Solution

We need to extract the python scripts from the executable file. In the tools folder, a program named `pyinstxtractor.py`is built just for that. Use the following command to unpack the executable:



In [4]:
python C:\Tools\pyinstxtractor.py ..\aisoudfwemidf.exe

C:\Tools\pyinstxtractor.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[*] Processing ..\aisoudfwemidf.exe
[*] Pyinstaller version: 2.1+
[*] Python version: 27
[*] Length of package: 3589441 bytes
[*] Found 21 files in CArchive
[*] Begining extraction...please standby
[!] Warning: The script is running in a different python version than the one used to build the executable
    Run this script in Python27 to prevent extraction errors(if any) during unmarshalling
[*] Found 204 files in PYZ archive
[*] Successfully extracted pyinstaller archive: ..\aisoudfwemidf.exe

You can now use a python decompiler on the pyc files within the extracted directory


Let's look at the files that were extracted:

In [3]:
Get-ChildItem -Path ..\aisoudfwemidf.exe_extracted



    Directory: C:\Users\Administrator\Artifacts\aisoudfwemidf.exe_extracted


Mode                LastWriteTime         Length Name                       
----                -------------         ------ ----                       
d-----        10/7/2019   8:32 AM                out00-PYZ.pyz_extracted    
-a----        10/7/2019   8:32 AM          35840 bz2.pyd                    
-a----        10/7/2019   8:32 AM          16384 Crypto.Cipher._AES.pyd     
-a----        10/7/2019   8:32 AM           8704 Crypto.Util._counter.pyd   
-a----        10/7/2019   8:32 AM           1050 microsoft.vc90.crt.manifest
-a----        10/7/2019   8:32 AM         225280 msvcm90.dll                
-a----        10/7/2019   8:32 AM         336016 msvcp90.dll                
-a----        10/7/2019   8:32 AM         251024 msvcr90.dll                
-a----        10/7/2019   8:32 AM         663244 out00-PYZ.pyz              
-a----        10/7/2019   8:32 AM              0 pyi-windows-manifest-fil

According to the the `pyinstxtractor.py` documentation, the main python file that contains the logic will usually be the file without any extension. In our case, that file is `ransomware`. Let's open the first 30 lines of this file with the following command:

In [1]:
Get-Content "..\aisoudfwemidf.exe_extracted\ransomware" -First 30

from Crypto.Cipher import AES
from Crypto.Util import Counter
import os
import ctypes
import time
import random
import base64
import _winreg as winreg


extensions = [
        # 'exe,', 'dll', 'so', 'rpm', 'deb', 'vmlinuz', 'img',  # SYSTEM FILES - BEWARE! MAY DESTROY SYSTEM!
        'jpg', 'jpeg', 'bmp', 'gif', 'png', 'svg', 'psd', 'raw', # images
        'mp3','mp4', 'm4a', 'aac','ogg','flac', 'wav', 'wma', 'aiff', 'ape', # music and sound
        'avi', 'flv', 'm4v', 'mkv', 'mov', 'mpg', 'mpeg', 'wmv', 'swf', '3gp', # Video and movies

        'doc', 'docx', 'xls', 'xlsx', 'ppt','pptx', # Microsoft office
        'odt', 'odp', 'ods', 'txt', 'rtf', 'tex', 'pdf', 'epub', 'md', # OpenOffice, Adobe, Latex, Markdown, etc
        'yml', 'yaml', 'json', 'xml', 'csv', # structured data
        'db', 'sql', 'dbf', 'mdb', # databases and disc images

        'html', 'htm', 'xhtml', 'php', 'asp', 'aspx', 'js', 'jsp', 'css', # web technologies
        'c', 'cpp', 'cxx', 'h', 'hpp', 'hxx', # C s

Notice "import base64", this gives a hint that the file probably has a base64 encoded object in it. Knowing that the base64 code is long, open the `ransomware` file in sublime text:

![Heren](pics/Heren9-1.png)

Below the base64 encoded object, there is a a function called "def set_wallpaper():"

#### Answer: base64

## <font color=green>Herensuge 10</font>

What type of the encryption does this ransomware use to encrypt a user's files? Don't include the mode of encryption. Include the key bit length in the encryption type if it is standard.

### Solution

Open the `ransomware` file from Herensuge 9

Scroll down until you notice the *encrypt_file* function. Reviewing this function you'll notice that *AES.new* references a variable named *key*.

![Heren](pics/Heren10-1.png)

Use the following command to locate the *key* variable:

In [8]:
Select-String -Path "..\aisoudfwemidf.exe_extracted\ransomware" -Pattern "key ="


C:\Users\Administrator\Artifacts\aisoudfwemidf.exe_extracted\ransomware:86: 
       registry_key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, path, 0, 
C:\Users\Administrator\Artifacts\aisoudfwemidf.exe_extracted\ransomware:96: 
       registry_key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, path, 0,
C:\Users\Administrator\Artifacts\aisoudfwemidf.exe_extracted\ransomware:107:
    key = os.urandom(32) # bytes object for encryption




After locating the variable *key*, you'll notice that it uses 32 bytes which is 256 bits.


#### Answer:  AES256

## <font color=green>Herensuge 11</font>

What are the first 8 characters of the Monero wallet owned by the hackers?

### Solution

Open the `ransomware` file from Herensuge 9 that contained the base64 encoded wallpaper. Copy and decode the base64 using CyberChef:

![Heren](pics/Heren9-1.png)

![Heren](pics/Heren11-1.png)

Download the file as a .png and open it. You'll notice the Monero wallet code at the bottom:

![Heren](pics/Heren38.png)

#### Answer: 42Sngtiq

## <font color=green>Herensuge 12</font>

What function was accidentally run in the first version of the ransomware sent by Hektor Elizondo (helizondo)? Give just the name of the function without parenthesis or parameters.

### Solution

Analyze the `ransomware` file in sublime. The file has a function called *decrypt_file*, the command below displays the function:

In [1]:
Get-Content "../aisoudfwemidf.exe_extracted/ransomware" | select -Last 19 -skip 70


def decrypt_file(new_file, filename, key, counter_start, blocksize = 32):

    ctr = Counter.new(128, initial_value=counter_start)
    decrypto = AES.new(key, AES.MODE_CTR, counter = ctr).decrypt
    f = open(filename, 'rb')
    decrypted_file = open(new_file, 'wb')
    plaintext = f.read(blocksize)
    while plaintext:
        ciphertext = decrypto(plaintext)
        if len(plaintext) != len(ciphertext):
            raise ValueError('''Ciphertext ({}) is not of the same length
                of the Plaintext ({}).
                Not a stream Cipher.'''.format(len(ciphertext), len(plaintext)))

        decrypted_file.write(ciphertext)
        plaintext = f.read(blocksize)
    f.close()
    decrypted_file.close()


This function had no logic statements and was run after the *encrypt_file* function. This caused the files to decrypt after being encrypted.  

#### Answer: decrypt_file